name: React Docker CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t react-app:${{ github.run_number }} .

      - name: Tag Image
        run: |
          docker tag react-app:${{ github.run_number }} \
          ${{ steps.login-ecr.outputs.registry }}/react-todo-app:${{ github.run_number }}

      - name: Push Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/react-todo-app:${{ github.run_number }}

      # updating the latest tag in IMAGE URI
      - name: Render ECS Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: react-todo-container
          image: ${{ steps.login-ecr.outputs.registry }}/react-todo-app:${{ github.run_number }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}